spring.application.name=BankingApp
#Mysql on ec2 instance
spring.datasource.url=jdbc:mysql://localhost:3306/bankingdata?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=appuser
spring.datasource.password=password123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=bXlTdXBlclNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uMTIzNDU2
security.jwt.expiration-time=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manuja2zlato@gmail.com
spring.mail.password=jhyk ljen jwrw ivkc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Local mysql
#spring.datasource.url=jdbc:mysql://localhost:3307/bankingdata?createDatabaseIfNotExist=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root